# C
COLOR_YELLOW = (255, 215, 0)
COLOR_WHITE = (255, 255, 255)

# M
MENU_OPTION = ('NEW GAME 1P - COOPERATIVE',
               'NEW GAME 2P - COOPERATIVE',
               'NEW GAME 2P - COMPETITIVE',
               'SCORE', 'EXIT')

# W
WIN_WIDTH = 576
WIN_HEIGHT = 324
